### ISSUE TITLE
Internal error has occured.

### ISSUE THREAD

**Issue by Qwer-TeX** [LunarVim/Neovim-from-scratch#319]
I installed Neovim-from-scratch. I then opened neovim and opened the config file.

I see this error pop up.

![Selection_001](https://github.com/LunarVim/Neovim-from-scratch/assets/128016252/6f9111e4-8e9e-4fd7-a6ad-e3fbd8af5cca)

Pressing enter shows the same error over again.

**Comment by gnmearacaun** [comment]
You could try running `:TSUpdate` to install missing language parsers

**Comment by Qwer-TeX** [comment]
Running `:TSUpdate` says `All parsers are up-to-date!`

So I typed `:TSInstall lua`. Then I don't see that error again.
